language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev" # 3.8 development branch
  - "nightly" # currently points to 3.8-dev
# command to install dependencies
env:
  - EDITABLE=-e
  - EDITABLE=
install: 
- pip install -U setuptools pip setuptools_scm pytest
- pip install $EDITABLE .
# command to run tests
script: pytest
